<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FreeTypeSharp" Version="3.1.0" />
    <PackageReference Include="GlmSharp" Version="0.9.8" />
    <PackageReference Include="SDL3-CS" Version="3.2.24" />
    <PackageReference Include="SDL3-CS.Native" Version="3.2.24" />
    <PackageReference Include="SDL3-CS.Native.Image" Version="3.2.4" />
    <PackageReference Include="SDL3-CS.Native.Mixer" Version="2.8.1.1" />
    <PackageReference Include="SDL3-CS.Native.TTF" Version="3.2.2" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="thirdparty/osx/**" Condition=" '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' ">
      <Link>runtimes/osx/native/%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/osx/native/%(Filename)%(Extension)</TargetPath>
    </Content>
    <Content Include="thirdparty/win64/**" Condition=" '$(OS)' == 'Windows_NT' ">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="thirdparty/linux/**" Condition=" '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' ">
      <Link>runtimes/linux-x64/native/%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>runtimes/linux-x64/native/%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="ruby ./embed_assets.rb" />
  </Target>

  <ItemGroup>
    <Compile Remove="**/Example*.cs" />
  </ItemGroup>

</Project>
